import { ReactNode } from "react";

import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import classNames from "classnames";

import "./globals.css";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={classNames("bg-black-primary", manrope.className)}>
        {children}
      </body>
    </html>
  );
}

type RootLayoutProps = {
  children: ReactNode;
};
